version: "3"
services:
  db:
    image: postgres:11.2-alpine
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    networks: 
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: todo
  web:
    build: .
    ports:
      - "8080:8080"
    networks: 
      - webnet
    environment:
      POSTGRES_HOST: db
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "server"]
networks: 
  webnet:
 