version: "3"
services:
  web:
    build: .
    depends_on:
      - db
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOSTNAME=db
      - POSTGRES_PORT=54321
      - POSTGRES_DB=todo
    ports:
      - "8080:8080"
    command: [ "node", "server.js" ]
    volumes:
      - ./dbdata:/var/lib/postgresql/data
  db:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo
    ports:
      - "54321:5432"