version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: todo
      POSTGRES_HOST: db
      POSTGRES_PORT: 54321
      
  web:
    build: ./server/
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    environment:
      POSTGRES_HOST: host.docker.internal
    command: ["npm","run","dev"]

  client:
    build:
      context: ./client/
    command: npm start
    depends_on:
      - web
    ports:
      - "3000:3000"