version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: todo
      POSTGRES_HOST: db
      POSTGRES_PORT: 54321
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    environment:
      POSTGRES_HOST: host.docker.internal
    command: ["npm", "start"]